services:
    [[APPLICATION]]-cache:
        image: valkey/valkey:9.0-alpine
        container_name: [[APPLICATION]]-cache
        ports:
            - "6379:6379"
        networks:
            - [[APPLICATION]]

    [[APPLICATION]]-db:
        image: mariadb:12.0.2-noble
        container_name: [[APPLICATION]]-db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=[[APPLICATION]]
            - MYSQL_HOST=[[APPLICATION]]-db
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "--password=root"]
        networks:
            - [[APPLICATION]]

    [[APPLICATION]]-testdb:
        image: mariadb:12.0.2-noble
        container_name: [[APPLICATION]]-testdb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=[[APPLICATION]]
            - MYSQL_HOST=[[APPLICATION]]-db
        ports:
            - "13306:3306"
        healthcheck:
            test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "--password=root"]
        networks:
            - [[APPLICATION]]

    [[APPLICATION]]-web:
        image: nginx:alpine
        container_name: [[APPLICATION]]-web
        working_dir: /application/src
        volumes:
            - .:/application
            - .docker/dev/nginx/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "8080:8080"
        depends_on:
            - [[APPLICATION]]-php
        networks:
            - [[APPLICATION]]

    [[APPLICATION]]-php:
        build:
            context: .docker/dev/php-fpm
        container_name: [[APPLICATION]]-php
        working_dir: /application/src
        volumes:
            - .:/application
            - ~/.composer/auth.json:/home/dockeruser/.composer/auth.json
        environment:
            XDEBUG_CONFIG: "client_host=host.docker.internal"
            PHP_IDE_CONFIG: "serverName=[[APPLICATION]]"
            COMPOSER_AUDIT_ABANDONED: "report"
            DOPPLER_TOKEN_IANHDEV: ${DOPPLER_TOKEN_IANHDEV:-''}
        depends_on:
            [[APPLICATION]]-db:
                condition: service_healthy
            [[APPLICATION]]-testdb:
                condition: service_healthy
            [[APPLICATION]]-cache:
                condition: service_started
        networks:
            - [[APPLICATION]]

    [[APPLICATION]]-mail:
        image: axllent/mailpit
        container_name: [[APPLICATION]]-mail
        working_dir: /application/src
        ports:
            - "18025:8025"
            - "1025:1025"
        networks:
            - [[APPLICATION]]

networks:
    [[APPLICATION]]:

